// <auto-generated />
using MaterialAssetsWarehouse.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaterialAssetsWarehouse.Migrations
{
    [DbContext(typeof(ItemDbContext))]
    [Migration("20240314181400_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MaterialAssetsWarehouse.Models.Item", b =>
                {
                    b.Property<int>("ItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemID"));

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Group")
                        .HasColumnType("int");

                    b.Property<int>("Measurement")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceWithoutVAT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StorageLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemID");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemID = 1043,
                            ContactPerson = "Andrzej Zalewski",
                            Group = 0,
                            Measurement = 4,
                            PriceWithoutVAT = 40m,
                            Quantity = 10,
                            Status = "available",
                            StorageLocation = "Warsaw"
                        },
                        new
                        {
                            ItemID = 4324,
                            ContactPerson = "Andrzej Zalewski",
                            Group = 1,
                            Measurement = 2,
                            PriceWithoutVAT = 60m,
                            Quantity = 30,
                            Status = "available",
                            StorageLocation = "Piaseczno"
                        },
                        new
                        {
                            ItemID = 5321,
                            ContactPerson = "Marek Kozłowksi",
                            Group = 3,
                            Measurement = 4,
                            PriceWithoutVAT = 65000m,
                            Quantity = 1,
                            Status = "available",
                            StorageLocation = "Warsaw"
                        },
                        new
                        {
                            ItemID = 2841,
                            ContactPerson = "Jarek Sannikov",
                            Group = 2,
                            Measurement = 1,
                            PriceWithoutVAT = 3259m,
                            Quantity = 100,
                            Status = "only 300 kg left",
                            StorageLocation = "Poznań"
                        },
                        new
                        {
                            ItemID = 4832,
                            ContactPerson = "Maria Ziobro",
                            Group = 1,
                            Measurement = 1,
                            PriceWithoutVAT = 249m,
                            Quantity = 3,
                            Status = "available",
                            StorageLocation = "Radom"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
